spring:
  main:
    banner-mode: "off"
  mvc:
    favicon:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    username: bostongene
    password: bostongene
    url: jdbc:postgresql://localhost:5432/bostongene

translation:
  yandex:
    key: XXX
    url: https://translate.yandex.net/api/v1.5/tr.json/
    detect: ${translation.yandex.url}detect?key=${translation.yandex.key}
    translate: ${translation.yandex.url}translate?key=${translation.yandex.key}